### ISSUE TITLE
Missing chipdata

### ISSUE THREAD

**Issue by colbro51** [Salamek/picpro#1]
Hi
I am trying to use your excellent software to program a PIC2C508A but I get an error:
ValueError: chipdata.cid was not found in any search path
for types "12c508", "12C508", "12c508a" and "12C508A".
Are you able to address this issue please?
Thanks
Colin

**Comment by Salamek** [comment]
@colbro51 hi, should be fixed in 0.0.6, please update and try again...

**Comment by colbro51** [comment]
Thanks.
I scouted around and found the file where it had installed under Linux Mint.  I added a link to it in /usr/lib/picpro and got it working already.  I might now add a gui interface using PySimpleGUI.

**Comment by Salamek** [comment]
Yea, chipdata.cid was installed in incorrect path in pre 0.0.6 versions...

Also some GUI would be nice (at least to show chip position in the programmer socket), i was planing to make a WebGUI for it in angular+Flask, but that may be YEARS away since i'm quite ok with CLI interface and have 0 time to mess around... so feel free to make GUI in PySimpleGUI if you have time for it ;-)
